apiVersion: v1
kind: Service
metadata: 
  name: survey-service
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8000
      name: http
  selector:
    name: survey-service
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: survey-service
spec:
  template:
    metadata:
      labels:
        name: survey-service
    spec:
      containers:
        - name: survey-service
          image: alikhil/survey-service
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata: 
  name: pg-service
spec:
  type: NodePort
  ports:
    - port: 5432
      name: http
  selector:
    name: pg-service
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: pg-service
spec:
  template:
    metadata:
      labels:
        name: pg-service
    spec:
      containers:
        - name: pg-service
          image: postgres
          ports:
            - containerPort: 5432